apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd 
spec: 
  project: default

  source: # the repo that hosts the app and the changes that might occur
    repoURL: https://github.com/Onsarouri/crud-app.git
    targetRevision: HEAD #last commits in my repo
    path: helm/myapp-docker

  destination: # kube cluster
    server: https://kubernetes.default.svc # the ArgoCD is deployed on the same cluster
    namespace: myapps 

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true 

  # Enabling automatic sync,
  automated: 
    selfHeal: true # Enabling automatic self-healing, by default changes made to the live cluster will not trigger automated sync
    prune: true # Enabling automatic pruning (by default automatic sync will not delete resources)

  # ArgoCD polls Git repo every 3 minutes, we can configure a Git webhook

---

apiVersion: v1 
kind: Secret
metadata:
  name: my-git-secret
  namespace: argocd
stringData:
  username: Onsarouri
  password: <your-personal-access-token>

---

apiVersion: argoproj.io/v1alpha1
kind: Repository
metadata:
  name: Onsarouri-crud-app-repo
  namespace: argocd
spec:
  type: git
  url: https://github.com/Onsarouri/crud-app.git
  usernameSecret:
    name: my-git-secret
    key: username
  passwordSecret:
    name: my-git-secret
    key: password
