apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: ons.arouriii@gmail.com
spec:
  project: default
  source:
    repoURL: https://github.com/Onsarouri/crud-app.git
    path: helm/myapp-docker
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
