apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-rolebinding
  namespace: myapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-role
subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd
