apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  triggers: |
    - name: on-sync-failed
      condition: app.status.operationState.phase in ['Error', 'Failed']
      template: app-sync-failed
    - name: on-sync-succeeded
      condition: app.status.operationState.phase == 'Succeeded'
      template: app-sync-succeeded
    - name: on-health-degraded
      condition: app.status.health.status == 'Degraded'
      template: app-health-degraded
    - name: on-sync-status-unknown
      condition: app.status.operationState.phase == 'Unknown'
      template: sync-status-unknown
  templates: |
    - name: app-sync-failed
      title: Application {{.app.metadata.name}} sync operation failed
      body: |
        Application {{.app.metadata.name}} sync operation failed.
        {{if .app.status.operationState.message}}Message: {{.app.status.operationState.message}}{{end}}
    - name: app-sync-succeeded
      title: Application {{.app.metadata.name}} sync operation succeeded
      body: |
        Application {{.app.metadata.name}} sync operation succeeded.
    - name: app-health-degraded
      title: Application {{.app.metadata.name}} has degraded health
      body: |
        Application {{.app.metadata.name}} health status is degraded.
        {{if .app.status.health.message}}Message: {{.app.status.health.message}}{{end}}
    - name: sync-status-unknown
      title: Application {{.app.metadata.name}} has unknown sync status
      body: |
        Application {{.app.metadata.name}} sync status is unknown.
  service.email: |
    hostSecret:
      name: email-credentials
      key: host
    portSecret:
      name: email-credentials
      key: port
    fromSecret:
      name: email-credentials
      key: from
    usernameSecret:
      name: email-credentials
      key: username
    passwordSecret:
      name: email-credentials
      key: password
    toSecret:
      name: email-credentials
      key: to