apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Onsarouri/crud-app.git
      type: git
      usernameSecret:
        name: email-credentials
        key: username
      passwordSecret:
        name: email-credentials
        key: password

  notifications: |
    configMap: argocd-notifications-cm
