apiVersion: v1
kind: Secret
metadata:
  name: argocd-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Onsarouri/crud-app.git
  username: argocd-private-repo  #name of the token
  password: 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 #the token
