image:
  repository: onsarouri/myapp-docker
  tag: latest
  pullPolicy: IfNotPresent

namespace: myapps

service:
  type: ClusterIP
  port: 8000

postgres:
  image: postgres:latest
  username: postgres
  password: admin
  database: NIDHAL
  port: 5432

ingress:
  enabled: false
  name: ""
  className: ""
  annotations: {}
  host: ""
  path: /
  tls: []
  extraHosts: []
  extraPaths: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources: {}
