apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-docker.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "myapp-docker.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "myapp-docker.name" . }}
    release: {{ .Release.Name }}

# Database Service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
